version: '3'

services:

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    environment:
      - NGROK_PORT=snappass:5000
    links:
      - snappass

  redis:
    image: redis:alpine

  snappass:
    image: nemoinho/snappass
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    ports:
      - 5000:5000
